pygments: true
permalink: pretty
markdown: kramdown

title: Josh Davis
name: Josh Davis's Personal Site
url: https://joshldavis.com
feed: /atom.xml

author: Josh Davis
contact:
    email: hello@joshldavis.com

css:
    - /css/base.css
    - /lib/font-awesome/css/font-awesome.min.css
    - http://fonts.googleapis.com/css?family=Droid+Sans:400,700

gems:
    - jekyll-redirect-from
    - jekyll-mentions

exclude:
    - README.md
    - TODO.md
    - LICENSE
