safe: true
pygments: true
permalink: pretty
markdown: rdiscount

title: Josh Davis
name: Josh Davis's Personal Site
url: http://joshldavis.com
feed: /atom.xml

author: Josh Davis
contact: hello@joshldavis.com

css:
    - /css/base.css
    - /lib/font-awesome/css/font-awesome.min.css
    - http://fonts.googleapis.com/css?family=Droid+Sans
