safe: true
pygments: true
permalink: pretty
markdown: rdiscount

title: Josh Davis
name: Josh Davis's Personal Site
url: http://joshldavis.com
feed: /atom.xml

author: Josh Davis
contact:
    email: hello@joshldavis.com
    facebook: https://www.facebook.com/joshd
    github: https://github.com/jdavis
    google: https://www.google.com/+JoshDavis9
    linkedin: https://www.linkedin.com/in/joshualeedavis
    twitter: https://twitter.com/HopefulJosh

css:
    - /css/base.css
    - /lib/font-awesome/css/font-awesome.min.css
    - http://fonts.googleapis.com/css?family=Droid+Sans:400,700

exclude:
    - README.md
    - TODO.md
    - LICENSE
